export const INIT_FETCH_SEARCH_RESULTS = 'INIT_FETCH_SEARCH_RESULTS'
export const FETCHING_SEARCH_RESULTS = 'FETCHING_SEARCH_RESULTS'
export const FETCHED_SEARCH_RESULTS = 'FETCHED_SEARCH_RESULTS'
export const FAILED_SEARCH_RESULTS = 'FAILED_SEARCH_RESULTS'


export const CURRENT_SELECTED_CATEGORY = 'CURRENT_SELECTED_CATEGORY'
export const ADD_TO_WATCH_LATER ='ADD_TO_WATCH_LATER'